# Generated by Django 3.2.5 on 2021-07-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.CharField(default='', max_length=100)),
                ('distance', models.CharField(default='', max_length=100)),
                ('interval', models.CharField(default='', max_length=100)),
                ('stroke', models.CharField(choices=[('free', 'Freestyle'), ('back', 'Backstroke'), ('breast', 'Breaststroke'), ('fly', 'Butterfly'), ('im', 'IM'), ('choice', 'Choice'), ('kick', 'Kick')], default='free', max_length=100)),
                ('equipment', models.CharField(choices=[('none', 'None'), ('kickboard', 'Kickboard'), ('bouy', 'Pull Bouy'), ('paddles', 'Paddles'), ('snorkel', 'Snorkel')], default='none', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
