# Generated by Django 3.2 on 2021-07-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='WorkoutSet',
        ),
    ]
