# Generated by Django 3.2 on 2021-07-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_rename_set_workoutset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('sets', models.ManyToManyField(to='workout.WorkoutSet')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
